(require '[braid.server.markdown :refer [markdown->hiccup]])
(require '[clojure.java.io :as io])

(defn generate-changelog
  []
  (let [changelog-hiccup (markdown->hiccup (slurp "CHANGELOG.md"))]
    (with-open [out-f (io/writer "src/braid/client/ui/views/pages/changelog.cljs")]
      (.write out-f "; THIS FILE IS AUTOMATICALLY GENERATED FROM CHANGELOG.md\n")
      (.write out-f "; DO NOT EDIT DIRECTLY\n")
      (.write out-f "; If git is complaining this file is updated, run\n")
      (.write out-f "; git update-index --assume-unchanged src/braid/client/ui/views/pages/changelog.cljs\n")
      (.write out-f (str '(ns braid.client.ui.views.pages.changelog) "\n"))
      (.write out-f (str (list 'defn 'changelog-view []
                           [:div.page.changelog
                            [:div.title "Changelog"]
                            [:div.content
                             changelog-hiccup]]))))))

(generate-changelog)
