; THIS FILE IS AUTOMATICALLY GENERATED FROM CHANGELOG.md
; DO NOT EDIT DIRECTLY

(ns braid.client.ui.views.pages.changelog)
(defn changelog-view [] [:div.page.changelog [:div.title "Changelog"] [:div.content [:div]]])
